---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-manager-sync
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-sync
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: cert-manager-sync
  namespace: cert-manager
roleRef:
  kind: Role
  name: cert-manager-sync
  apiGroup: rbac.authorization.k8s.io
